name: Testing Daniel Labels

on:
  push:
  pull_request:
    types:
      - labeled
      - opened
      - synchronize

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  haslabel:
    name: Has Labels
    runs-on: ubuntu-latest

    outputs:
      jenkins: ${{ steps.label-jenkins.outputs.labeled-jenkins }}
      smoke: ${{ steps.label-smoke.outputs.labeled-smoke }}
      build: ${{ steps.label-build.outputs.labeled-build }}

    steps:
      - uses: actions/checkout@v2

      - name: Labeled to jenkins
        id: label-jenkins
        uses: DanielTamkin/HasLabel@v1.0.4
        with:
          contains: 'jenkins'

      - name: Labeled to Smoke
        id: label-smoke
        uses: DanielTamkin/HasLabel@v1.0.4
        with:
          contains: 'Smoke'

      - name: Labeled to jenkins
        id: label-build
        uses: DanielTamkin/HasLabel@v1.0.4
        with:
          contains: 'Integration'

  jenkins:
    name: Jenkins
    needs: haslabel
    if: needs.haslabel.outputs.jenkins
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v2

      - name: Jenkins
        run: echo "jenkins label is here :)"
   
  smoke:
    name: Smoke
    needs: haslabel
    if: needs.haslabel.outputs.smoke
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v2

      - name: Smoke
        run: echo "Smoke label is here :)"

  build:
    name: Integration
    needs: haslabel
    if: needs.haslabel.outputs.build
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v2

      - name: Integration
        run: echo "Integration label is here :)"

  jenkins-smoke:
    name: Call Jenkins Job
    needs: haslabel
    if: needs.haslabel.outputs.jenkins || needs.haslabel.outputs.smoke
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v2

      - name: Jenkins or Smoke
        run: echo "jenkins or Smoke label is here :)"
