name: Integration Suite

on:
 pull_request:
  types:
    - opened
    - synchronize
    - labeled
  branches:
    - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  has-label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Labeled to jenkins
        id: label-jenkins
        uses: DanielTamkin/HasLabel@v1.0.4
        with:
          contains: 'jenkins'

      - name: Labeled to Smoke
        id: label-smoke
        uses: DanielTamkin/HasLabel@v1.0.4
        with:
          contains: 'Smoke'

      - name: Labeled to jenkins
        id: label-build
        uses: DanielTamkin/HasLabel@v1.0.4
        with:
          contains: 'build'

  build:
    name: Build the App
    needs: has-label
    # if: needs.haslabel.outputs.build
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v2

      - name: Run commands to build the application
        run: echo "Building the App :)"
 
      - name: Echo the labels
        run: echo "${{ needs.haslabel.outputs.build }}"
   
  test:
    name: Test the App
    needs: has-label
    # if: needs.haslabel.outputs.build
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v2

      - name: Run commands to test the application
        run: echo "Calling Jenkins Job :)"

      - name: Echo the labels
        run: echo "${{ needs.haslabel.outputs.build }}"

  jenkins:
    name: Call Jenkins Job
    needs: [build, test, has-label]
    # if: needs.haslabel.outputs.jenkins || needs.haslabel.outputs.smoke
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v2

      - name: Call the Jenkins Job to Build Docker Images
        run: echo "Calling Jenkins Job :)"

      - name: Echo the labels
        run: |
          echo "${{ needs.haslabel.outputs.jenkins }}"
          echo "${{ needs.haslabel.outputs.Smoke }}"

