name: Labels

on:
  push:
  pull_request:
    types:
      - labeled

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  check_pr_labels_job:
    runs-on: ubuntu-latest
    name: A job to check the PR labels contain given labels
    steps:
    - name: Check PR labels action step
      id: check_pr_labels
      uses: shioyang/check-pr-labels-on-push-action@v1.0.6
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        labels: '["jenkins"]'
    - name: See result
      run: echo "${{ steps.check_pr_labels.outputs.result }}"

  build:
    name: Build Label
    if: "contains(github.event.pull_request.labels.*.name, 'Build')"
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v2

      - name: Check the Build label
        run: echo "Build label is here! :)"
   
  smoke:
    name: Smoke Label
    if: "contains(github.event.pull_request.labels.*.name, 'Smoke')"
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v2

      - name: Check the Smoke label
        run: echo "Smoke label is here! :)"

  jenkins:
    name: jenkins Label
    if: "contains(github.event.pull_request.labels.*.name, 'jenkins')"
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v2

      - name: Check the Jenkins label
        run: echo "jenkins label is here! :)"
