name: Labels

on:
  push:
  pull_request:
    types:
      - labeled

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  build:
    name: Build the App
    if: contains(github.event.pull_request.labels.*.name, 'Build') || ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v2

      - name: Run commands to build the application
        run: echo "Building the App :)"
   
  smoke:
    name: Smoke Job
    if: contains(github.event.pull_request.labels.*.name, 'Smoke') || ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v2

      - name: Run commands to test the application
        run: echo "Calling Jenkins Job to run Smoke Tests :)"

  jenkins:
    name: Call Jenkins Job
    if: contains(github.event.pull_request.labels.*.name, 'jenkins') || ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v2

      - name: Call the Jenkins Job to Build Docker Images
        run: echo "Calling Jenkins Job :)"
